# SPDX-FileCopyrightText: © 2024 Alexandros Theodotou <alex@zrythm.org>
# SPDX-License-Identifier: LicenseRef-ZrythmLicense

workflow:
  rules:
    # run merge request pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # do not run branch pipelines if corresponding merge requests exist...
    # (this avoids duplicate pipelines)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # ...but otherwise run branch pipelines
    - if: $CI_COMMIT_BRANCH
    # run tag pipelines
    - if: $CI_COMMIT_TAG

variables:
  COMMON_CMAKE_OPTIONS: >-
    -DZRYTHM_STRICT=ON
    -DZRYTHM_TESTS=ON
    -DZRYTHM_BENCHMARKS=ON
    -DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER

stages:
  - setup
  - check
  - build # also test
  - deploy

.unix-activate-venv: &unix-activate-venv
  - source ./venv/bin/activate

.windows-activate-venv: &windows-activate-venv
  - ./venv/Scripts/Activate.ps1

# .mac-enable-brew-env: &mac-enable-brew-env
  # - eval "$(/opt/homebrew/bin/brew shellenv)";

.windows-enable-vs-env: &windows-enable-vs-env
  - Import-Module "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
  - >-
    Enter-VsDevShell
    -VsInstallPath "C:\Program Files\Microsoft Visual Studio\2022\Community"
    -SkipAutomaticLocation
    -DevCmdArguments -arch=x64
  #- chcp 65001 # UTF-8

.gnu-linux-template:
  tags:
    - archlinux
  variables:
    BUILDDIR: "build_gnu_linux"
    QT_QPA_PLATFORM: "offscreen"
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - *unix-activate-venv

.mac-arm-template:
  tags:
    - mac-arm
  variables:
    BUILDDIR: "build_mac_arm"
    BOOST_ROOT: "/opt/boost/boost_1_88_0/installed"
  before_script:
    - *unix-activate-venv

.windows-template:
  tags:
    - windows11
  variables:
    BUILDDIR: "build_windows"
    INSTALLDIR: "install_windows"
    BOOST_ROOT: "C:\\Boost\\boost_1_86_0"
    VSLANG: "1033"
    # use /MP1 to disable parallel builds if the compiler messages are hard to read
    CL: "/MP" # prepended to the cl command
    _CL_: "" # appended to the cl command
    _LINK_: ""
  before_script:
    - *windows-enable-vs-env
    - *windows-activate-venv

default:
  cache:
  # this number must be bumped every time these subprojects are updated
  - key: cache-14-$CI_RUNNER_DESCRIPTION
    paths:
      - venv
      - '${BUILDDIR}-*/_deps/*-src'

configure:gnu/linux:
  extends: .gnu-linux-template
  stage: setup
  before_script:
    - python3 -m venv venv
    - *unix-activate-venv
    - python3 -m pip install -r requirements.txt
  script:
    - >-
      cmake -B ${BUILDDIR}-${BUILD_TYPE} ${COMMON_CMAKE_OPTIONS}
      -G "Ninja"
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_PREFIX_PATH=/opt/Qt6.9
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DZRYTHM_USER_MANUAL=ON
      -DZRYTHM_STRICT_SPHINX_OPTS=ON
      -DZRYTHM_UNITY_BUILD=ON
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]
  artifacts:
    paths:
      - ${BUILDDIR}-${BUILD_TYPE}
    exclude:
      - ${BUILDDIR}-${BUILD_TYPE}/**/.git/**/*
    expire_in: 1 day

configure:mac-arm:
  extends: .mac-arm-template
  stage: setup
  before_script:
    - python3 -m venv venv
    - *unix-activate-venv
    - python3 -m pip install -r requirements.txt
  script:
    - >-
      cmake -B ${BUILDDIR}-${BUILD_TYPE} ${COMMON_CMAKE_OPTIONS}
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -G "Xcode"
      "-DCMAKE_PREFIX_PATH=/opt/homebrew/Cellar/lv2/1.18.10;/opt/Qt6.9"
      -DZRYTHM_UNITY_BUILD=ON
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]
  artifacts:
    paths:
      - ${BUILDDIR}-${BUILD_TYPE}
    exclude:
      - ${BUILDDIR}-${BUILD_TYPE}/**/.git/**/*
    expire_in: 1 day

configure:windows:
  extends: .windows-template
  stage: setup
  before_script:
    - *windows-enable-vs-env
    - python -m venv venv
    - *windows-activate-venv
    - python -m pip install -r requirements.txt
  script:
    - >-
      cmake -B "${env:BUILDDIR}-${env:BUILD_TYPE}"
      -DZRYTHM_STRICT=ON
      -DZRYTHM_TESTS=ON
      -DZRYTHM_BENCHMARKS=ON
      -DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER
      -DZRYTHM_FFTW3_THREADS_SEPARATE=FALSE
      "-DCMAKE_PREFIX_PATH=C:\Qt\Qt-6.9.0-${env:BUILD_TYPE};C:\lv2"
      -G "Visual Studio 17 2022"
      -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL"
      "-DCMAKE_MSVCIDE_RUN_PATH=C:\Qt\Qt-6.9.0-${env:BUILD_TYPE}\bin"
      "-DCMAKE_BUILD_TYPE=${env:BUILD_TYPE}"
      "-DCMAKE_INSTALL_PREFIX=${PWD}\${env:INSTALLDIR}"
      -DZRYTHM_UNITY_BUILD=ON
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]
  artifacts:
    paths:
      - ${BUILDDIR}-${BUILD_TYPE}
    exclude:
      - ${BUILDDIR}-${BUILD_TYPE}/**/.git/**/*
    expire_in: 1 day

clazy-check:
  extends: .gnu-linux-template
  stage: check
  needs: []
  script:
    - export CLAZY_CHECKS="level1"
    - >-
      cmake -B build_clazy ${COMMON_CMAKE_OPTIONS}
      -G "Ninja"
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clazy
      -DCMAKE_PREFIX_PATH=/opt/Qt6.9
      -DCMAKE_BUILD_TYPE=Debug
      -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON
      -DZRYTHM_UNITY_BUILD=OFF
      -DZRYTHM_DISABLE_CCACHE=ON
    - cmake --build build_clazy --parallel || true # TODO

clang-format-check:
  extends: .gnu-linux-template
  stage: check
  needs: []
  script:
    - python3 scripts/run_clang_format.py --dry-run

reuse-check:
  extends: .gnu-linux-template
  stage: check
  needs: []
  script:
   - reuse lint

exif-check:
  extends: .gnu-linux-template
  stage: check
  needs: []
  script:
   - scripts/exif_check.sh

.unix_test_cmd: &unix_test_cmd
  - ctest --test-dir ${BUILDDIR}-${BUILD_TYPE} -V || (cat "${BUILDDIR}-${BUILD_TYPE}/Testing/Temporary/LastTest.log" && exit 1)

clang-tidy-check:
  extends: .gnu-linux-template
  stage: check
  needs:
    - job: configure:gnu/linux
      artifacts: true
  script:
    - >-
      git diff -U0 HEAD^
      | python3 /usr/share/clang/clang-tidy-diff.py -p1
      -path ${BUILDDIR}-Debug -config-file .clang-tidy
      -use-color

build:gnu/linux:
  extends: .gnu-linux-template
  stage: build
  needs:
    - job: configure:gnu/linux
      artifacts: true
    - job: exif-check
    - job: reuse-check
    - job: clang-format-check
  script:
    - cmake --build ${BUILDDIR}-${BUILD_TYPE} --parallel
    - *unix_test_cmd
    - >-
      ctest --test-dir ${BUILDDIR}-${BUILD_TYPE} -V
      --overwrite MemoryCheckCommandOptions="--undef-value-errors=no --exit-on-first-error=yes --error-exitcode=1"
      -T memcheck -E "appstream-util-validate-appdata"
      || (cat "${BUILDDIR}-${BUILD_TYPE}/Testing/Temporary/MemoryChecker.*.log" && exit 1)
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]

build:mac-arm:
  extends: .mac-arm-template
  stage: build
  needs:
    - job: configure:mac-arm
      artifacts: true
  script:
    - cmake --build ${BUILDDIR}-${BUILD_TYPE} --config ${BUILD_TYPE} --parallel
    - *unix_test_cmd
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]

build:windows:
  extends: .windows-template
  stage: build
  needs:
    - job: configure:windows
      artifacts: true
  script:
    - cmake --build "${env:BUILDDIR}-${env:BUILD_TYPE}" --config "${env:BUILD_TYPE}" --parallel -- /verbosity:minimal "/consoleLoggerParameters:NoSummary;ForceConsoleColor"
    - if (! $?) { exit 1 }  # Check if the previous command failed
    # copy DLLs and resources needed at runtime for tests, etc.
    - '& "C:\Qt\Qt-6.9.0-${env:BUILD_TYPE}\bin\windeployqt.exe" --qmldir "${env:BUILDDIR}-${env:BUILD_TYPE}" --pdb --force -qml -widgets -quick -quickwidgets "${env:BUILDDIR}-${env:BUILD_TYPE}\${env:BUILD_TYPE}\zrythm.exe"'
    - ctest --test-dir "${env:BUILDDIR}-${env:BUILD_TYPE}" -C "${env:BUILD_TYPE}" -V; if (-not $?) { Get-Content "${env:BUILDDIR}-${env:BUILD_TYPE}/Testing/Temporary/LastTest.log"; exit 1 }
  parallel:
    matrix:
      - BUILD_TYPE: [Debug, Release]

update-manual:
  extends: .gnu-linux-template
  stage: deploy
  only:
    - master
    - tags
  needs:
    - job: build:gnu/linux
    - job: configure:gnu/linux
      artifacts: true
  script:
    - ninja -C ${BUILDDIR}-Debug manual_bundle &> manual_bundle_results.txt || (cat manual_bundle_results.txt && exit 1)
    - rsync -av --no-group --omit-dir-times --exclude '*.zip' "${BUILDDIR}-Debug"/doc/user/_rendered/* $REMOTE_CI_USER@www.zrythm.org:$REMOTE_USER_MANUAL_UPLOAD_PATH
  before_script:
    - eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_PRIVATE_KEY")
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - *unix-activate-venv

update-dev-docs:
  extends: .gnu-linux-template
  stage: deploy
  only:
    - master
    - tags
  needs:
    - update-manual
  script:
    - cmake --build ${BUILDDIR}-Debug --target doxygen-docs &> gen_dev_docs_results.txt || (cat gen_dev_docs_results.txt && exit 1)
    - rsync -av --no-group --omit-dir-times "${BUILDDIR}-Debug"/doc/dev/html/* $REMOTE_CI_USER@www.zrythm.org:$REMOTE_DEV_DOCS_UPLOAD_PATH
  before_script:
    - eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_PRIVATE_KEY")
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - *unix-activate-venv